# Generated by Django 4.2.3 on 2023-07-28 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id_char", models.CharField(max_length=150)),
                ("title", models.CharField(db_column="title", max_length=50)),
                ("content", models.TextField(db_column="content", default="")),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="created_date"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, db_column="updated_date"),
                ),
                (
                    "updated_bool",
                    models.BooleanField(db_column="updated_bool", default=False),
                ),
                (
                    "visible_bool",
                    models.BooleanField(db_column="visible_bool", default=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id_char", models.CharField(max_length=150)),
                ("comment_content", models.CharField(max_length=300)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "updated_bool",
                    models.BooleanField(db_column="updated_bool", default=False),
                ),
                (
                    "visible_bool",
                    models.BooleanField(db_column="visible_bool", default=True),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="boards.post",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
